server:
  port: ${MARTY-PORT:8080}
  servlet:
    contextPath: /

spring:
  profiles:
     active: ${MARTY-PROFILE:hml}
  application:
    name: Marty 
  
jdbc:
  wis:    
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:${MARTY-WIS-URL:thin:@//mlhsi2pkg.magazineluiza.intranet:1550/WIS}    
    username: ${MARTY-WIS-USERNAME:USR_MARTY}
    password: ${MARTY-WIS-PASSWORD:0vhlroCgRHjw!aWt}
    removeAbandoned: true
    removeAbandonedTimeout: 120
    logAbandoned: true
    maxPoolSize:  ${MARTY-WIS-MAXPOOLSIZE:10} 
    idleTimeout: ${MARTY-WIS-IDLETIMEOUT:10000} 
    connectionTimeout: ${MARTY-WIS-CONNECTION:20000}
    minimumIdle: ${MARTY-WIS-MINIDLE:20000} 
    validationQuery: "select sysdate from dual"
    testOnBorrow: true
    testOnConnect: true
    testWhileIdle: true
  erp:    
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:${MARTY-ERP-URL:thin:@//mlsrvibm1.magazineluiza.intranet:8001/MLHDB}    
    username: ${MARTY-ERP-USERNAME:USR_MARTY}
    password: ${MARTY-ERP-PASSWORD:0nVABLmKPx2PK3V}
    removeAbandoned: true
    removeAbandonedTimeout: 120
    logAbandoned: true
    maxPoolSize:  ${MARTY-ERP-MAXPOOLSIZE:10} 
    idleTimeout: ${MARTY-ERP-IDLETIMEOUT:10000} 
    connectionTimeout: ${MARTY-ERP-CONNECTION:20000}
    minimumIdle: ${MARTY-ERP-MINIDLE:20000} 
    validationQuery: "select sysdate from dual"
    testOnBorrow: true
    testOnConnect: true
    testWhileIdle: true

endpoints:
  health:
    sensitive: false

management:
  endpoint:
    health:
      show-details: always
  security:
    enabled: false

security:
  user:
    name: ${MARTY-SECURITY-USERNAME}
    password: ${MARTY-SECURITY-PASSWORD}
  jwt:
      uri: "/**"
      header: ${MARTY-JWT-HEADER:Authorization}
      prefix: ${MARTY-JWT-PREFIX:Bearer}
      secret: ${MARTY-JWT-SECRET:ade0b6e310c0a3a83583cf3523ffc27c}

bztoken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHAiOiJtYXJ0eSIsInRlYW0iOiJzcXVhZC1hcm1hemVtIn0.EWRmTZLhVb-6WmkCRv3A6S6zpjdGipBIRFxI6eogPLo

info:
  app:
    encoding: '@project.build.sourceEncoding@'
  java:
    source: '@java.version@'
    target: '@java.version@'
  build:
    artifact: '@project.artifactId@'
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    

